In [1]:
import pandas as pd
reviews = pd.read_excel("./reviews.xlsx")
pd.set_option('display.max_rows', 5)

In [ ]:
reviews.groupby('points'): This part groups the DataFrame reviews based on the values in the points column. 
In essence, it creates subsets of the data where each subset contains rows with the same points value.

.points: This specifies that we're interested in the points column within each of the created groups.

.count(): This counts the number of rows (or occurrences) within each of the points groups.

In [20]:
# Counts how many times each unique point value appears in the dataset.
# reviews['points'].value_counts() 
# or reviews.groupby('points').points.count() 
# or reviews.groupby('points').size() 
# or reviews.pivot_table(index='points', aggfunc='size')

reviews.points
reviews.groupby('points').points.count()

points
87    2
88    2
     ..
92    2
93    2
Name: points, Length: 7, dtype: int64

In [32]:
# reviews.groupby('points')
# : Groups the DataFrame reviews by the points column, creating subsets for each unique point value.
# .price: Selects the price column within each group.
# .min(): Calculates the minimum value (price) for each group.
# or
# min_prices = reviews.groupby('points')['price'].apply(lambda x: x.min())
# print(min_prices)
# or
# min_prices = reviews.groupby('points')['price'].agg('min')
# print(min_prices)
# or
# min_prices = reviews.pivot_table(values='price', index='points', aggfunc='min')
# print(min_prices)
    
reviews.groupby('points').price.min()

points
87    15.0
88    16.0
      ...
92    23.0
93    24.0
Name: price, Length: 7, dtype: float64

In [37]:
# reviews.groupby(['country', 'province'])
# : This part groups the DataFrame reviews based on the values in both the country and province columns, creating subsets for each unique combination of country and province.
# .description: This specifies that we're interested in the description column within each group.
# .agg([len]): This applies the len function (which calculates the length of a string) to the description column within each group.

reviews.groupby(['country', 'province']).description.agg([len])

                            len
country  province
France   Alsace               8
Italy    Sicily & Sardinia    4
Portugal Douro                4

In [42]:
mi = countries_reviewed.index
type(mi)

pandas.core.indexes.multi.MultiIndex

In [43]:
countries_reviewed.reset_index()

    country           province  len
0    France             Alsace    8
1     Italy  Sicily & Sardinia    4
2  Portugal              Douro    4

In [44]:
countries_reviewed = countries_reviewed.reset_index()
countries_reviewed.sort_values(by='len')

    country           province  len
1     Italy  Sicily & Sardinia    4
2  Portugal              Douro    4
0    France             Alsace    8

In [45]:
countries_reviewed.sort_values(by='len', ascending=False)

    country           province  len
0    France             Alsace    8
1     Italy  Sicily & Sardinia    4
2  Portugal              Douro    4

In [46]:
countries_reviewed.sort_index()

    country           province  len
0    France             Alsace    8
1     Italy  Sicily & Sardinia    4
2  Portugal              Douro    4

In [47]:
countries_reviewed.sort_values(by=['country', 'len'])

    country           province  len
0    France             Alsace    8
1     Italy  Sicily & Sardinia    4
2  Portugal              Douro    4