In [2]:
import pandas as pd
reviews = pd.read_excel("./reviews.xlsx")
pd.set_option('display.max_rows', 5)

In [28]:
reviews

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,93,35.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
15,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,93,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [36]:
reviews['country']
# reviews['country'] = reviews.country

0        Italy
1     Portugal
        ...
14      France
15      France
Name: country, Length: 16, dtype: object

In [39]:
# reviews['country'][0] = reviews.country[0] 
reviews.country[0]

'Italy'

In [ ]:
iloc

    Integer-based indexing: Uses integer positions to select rows and columns.
    Zero-based: Starts counting from 0.
    Slicing: Can use slicing operations with integers.
    Syntax: df.iloc[row_indexer, column_indexer]

loc

    Label-based indexing: Uses column and index names to select data.
    Inclusive: Includes both the start and end points in slicing.
    Slicing: Can use slicing operations with labels.
    Syntax: df.loc[row_indexer, column_indexer]

In [44]:
# .iloc: This is a Pandas method used for integer-based indexing.
# [0]: Selects the row at index 0 (which is the first row).
reviews.iloc[0]

country                                                    Italy
description    Aromas include tropical fruit, broom, brimston...
                                     ...
variety                                              White Blend
winery                                                   Nicosia
Name: 0, Length: 13, dtype: object

In [45]:
# .iloc: This is a Pandas method used for integer-based indexing.
# [:, 0]: This specifies the slicing of the DataFrame:

#     : selects all rows.
#     0 selects the first column.
reviews.iloc[:, 0]

0        Italy
1     Portugal
        ...
14      France
15      France
Name: country, Length: 16, dtype: object

In [46]:
# [:3, 0]: Specifies the slicing of the DataFrame:

#     :3: Selects rows from the beginning up to, but not including, row 3 (i.e., rows 0, 1, and 2).
#     0: Selects the first column.
reviews.iloc[:3, 0]

0       Italy
1    Portugal
2      France
Name: country, dtype: object

In [47]:
# [1:3, 0]: Specifies the slicing of the DataFrame:

#     1:3: Selects rows from index 1 (inclusive) up to, but not including, index 3 (i.e., rows 1 and 2).
#     0: Selects the first column.
reviews.iloc[1:3, 0]

1    Portugal
2      France
Name: country, dtype: object

In [48]:
    # [[0, 1, 2], 0]: Specifies the slicing of the DataFrame:
    #     [0, 1, 2]: Selects rows at indices 0, 1, and 2.
    #     0: Selects the first column.

reviews.iloc[[0, 1, 2], 0]

0       Italy
1    Portugal
2      France
Name: country, dtype: object

In [49]:
# [-5:]: Selects rows starting from the fifth row from the end (inclusive) to the end of the DataFrame.
reviews.iloc[-5:]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
11,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,92,23.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit
12,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,90,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
13,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,90,18.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
14,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,93,35.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
15,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,93,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [54]:
# .loc: Label-based location indexing method in Pandas.
# [0, 'country']: Specifies the location of the value you want to access:

#     0: Selects the row with the label (or index) 0.
#     'country': Selects the column named 'country'.
reviews.loc[0, 'country']

'Italy'

In [55]:
# .loc: Label-based location indexing method in Pandas.
# [:, ['taster_name', 'taster_twitter_handle', 'points']]: Specifies the slicing of the DataFrame:

#     :: Selects all rows.
#     ['taster_name', 'taster_twitter_handle', 'points']: Selects the columns named 'taster_name', 'taster_twitter_handle', and 'points'.
reviews.loc[:, ['taster_name', 'taster_twitter_handle', 'points']]

      taster_name taster_twitter_handle  points
0   Kerin O’Keefe          @kerinokeefe      87
1      Roger Voss            @vossroger      87
..            ...                   ...     ...
14     Roger Voss            @vossroger      93
15     Roger Voss            @vossroger      93

[16 rows x 3 columns]

In [4]:
# The "title" column, which was previously a regular column, becomes the row labels.
# sets the "title" column as the index of the DataFrame
reviews.set_index("title")

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
title,,,,,,,,,,,,
Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...
Domaine Marcel Deiss 2012 Pinot Gris (Alsace),France,"A dry style of Pinot Gris, this is crisp with ...",NaN,93,35.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Pinot Gris,Domaine Marcel Deiss
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,93,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Gewürztraminer,Domaine Schoffit

In [32]:
# selects rows from the DataFrame reviews where the value in the 'country' column is 'Italy'
# reviews.country == 'Italy' 
# or reviews['country'] == 'Italy'
reviews.country == 'Italy'

0      True
1     False
      ...
14    False
15    False
Name: country, Length: 16, dtype: bool

In [28]:
# reviews.country: This part accesses the 'country' column of the DataFrame reviews.
# reviews.country == 'Italy': This creates a Boolean Series where each element is True if the corresponding country is 'Italy', 
# otherwise False.
# reviews.loc[ ]: This is using the .loc indexer to select rows based on conditions.
# reviews.loc[reviews.country == 'Italy']: This combines the above steps, using the Boolean Series created in step 2 to select rows 
# where the condition is True

# reviews.loc[reviews.country == 'Italy'] 
# or reviews[reviews['country'] == 'Italy'] 
# or reviews.query("country == 'Italy'") 
# or reviews[reviews['country'].isin(['Italy'])]

reviews.loc[reviews.country == 'Italy']

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,16
4,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,88,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,12
8,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,89,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,8
12,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,90,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,4

In [14]:
# reviews.country == 'Italy': This part remains the same, filtering for rows where the 'country' column equals 'Italy'.
# reviews.points >= 90: This selects rows where the 'points' column is greater than or equal to 90.
# &: The & symbol represents the logical AND operator. It ensures that only rows meeting both conditions (Italy and high points) are included.
# reviews.loc[...]: This uses .loc to select rows based on the combined Boolean conditions.
reviews.loc[(reviews.country == 'Italy') & (reviews.points >= 90)]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
12,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,90,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia

In [38]:
# reviews.loc[(reviews.country == 'Italy') | (reviews.points >= 90)]
# or reviews[(reviews['country'] == 'Italy') | (reviews['points'] >= 90)]
reviews.query("country == 'Italy' or points >= 90")

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,16
4,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,88,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,12
8,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,89,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,8
12,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,90,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,4

In [41]:
# reviews.loc[reviews.country.isin(['Italy', 'France'])]
# or 
# countries = ['Italy', 'France']
# reviews[reviews['country'].isin(countries)]
# or reviews.query("country in @countries")
# or reviews[reviews['country'].astype(str).isin(countries)]
reviews.loc[reviews.country.isin(['Italy', 'France'])]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,16
2,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,everyone,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,93,35.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,everyone,2
15,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,93,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,everyone,1

In [17]:
reviews.loc[reviews.price.notnull()]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,93,35.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
15,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,93,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [18]:
reviews['critic'] = 'everyone'
reviews['critic']

0     everyone
1     everyone
        ...
14    everyone
15    everyone
Name: critic, Length: 16, dtype: object

In [19]:
# reviews['index_backwards'] = range(len(reviews), 0, -1): This line creates a new column in the DataFrame reviews called index_backwards. 
# The values in this column are generated using the range function.

#     len(reviews): Calculates the number of rows in the DataFrame.
#     0: Specifies the ending value for the range (exclusive).
#     -1: Determines the step size, which is -1, meaning the sequence will count backward.
reviews['index_backwards'] = range(len(reviews), 0, -1)
reviews['index_backwards']

0     16
1     15
      ..
14     2
15     1
Name: index_backwards, Length: 16, dtype: int64