In [1]:
# https://colab.research.google.com/notebooks/io.ipynb
# Uploading files from local file system.
from google.colab import files
uploaded = files.upload()
for fn in uploaded.keys():
  print('Uploaded file "{name}" with length {length} bytes'.format(name=fn, length=len(uploaded[fn])))

Saving Titanic-train.csv to Titanic-train (1).csv
Uploaded file "Titanic-train.csv" with length 61194 bytes

In [2]:
import pandas as pd
# Following code converts the uploaded file into a pandas dataframe.
# Make sure the filename matches the name of the uploaded file.
import io
titanic_df = pd.read_csv(io.BytesIO(uploaded["Titanic-train.csv"]))
# Dataset is now stored in a Pandas Dataframe

In [3]:
titanic_df
# When displaying a DataFrame, the first and last 5 rows will be shown by default.

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [4]:
titanic_df.drop_duplicates()

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [5]:
titanic_df.head()
# Displaying the first 5 rows of a pandas DataFrame
# Want to see the first 8 rows of a pandas DataFrame.
# titanic_df.head(8)

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [6]:
titanic_df.tail()
# Displaying the last 5 rows of a pandas DataFrame

     PassengerId  Survived  Pclass  ...   Fare Cabin  Embarked
886          887         0       2  ...  13.00   NaN         S
887          888         1       1  ...  30.00   B42         S
888          889         0       3  ...  23.45   NaN         S
889          890         1       1  ...  30.00  C148         C
890          891         0       3  ...   7.75   NaN         Q

[5 rows x 12 columns]

In [7]:
#  Displaying list of column names 
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [8]:
# Display shape of DataFrame
titanic_df.shape

(891, 12)

In [9]:
titanic_df.info()
# The method info() provides technical information about a DataFrame.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [10]:
titanic_df.isnull() # Returns True & False

     PassengerId  Survived  Pclass   Name  ...  Ticket   Fare  Cabin  Embarked
0          False     False   False  False  ...   False  False   True     False
1          False     False   False  False  ...   False  False  False     False
2          False     False   False  False  ...   False  False   True     False
3          False     False   False  False  ...   False  False  False     False
4          False     False   False  False  ...   False  False   True     False
..           ...       ...     ...    ...  ...     ...    ...    ...       ...
886        False     False   False  False  ...   False  False   True     False
887        False     False   False  False  ...   False  False  False     False
888        False     False   False  False  ...   False  False   True     False
889        False     False   False  False  ...   False  False  False     False
890        False     False   False  False  ...   False  False   True     False

[891 rows x 12 columns]

In [11]:
titanic_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [12]:
titanic_df["Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [13]:
type(titanic_df["Name"])
# Each column in a DataFrame is a Series.

pandas.core.series.Series

In [14]:
titanic_df[["Name", "Age", "Sex"]]

                                                  Name   Age     Sex
0                              Braund, Mr. Owen Harris  22.0    male
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
2                               Heikkinen, Miss. Laina  26.0  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
4                             Allen, Mr. William Henry  35.0    male
..                                                 ...   ...     ...
886                              Montvila, Rev. Juozas  27.0    male
887                       Graham, Miss. Margaret Edith  19.0  female
888           Johnston, Miss. Catherine Helen "Carrie"   NaN  female
889                              Behr, Mr. Karl Howell  26.0    male
890                                Dooley, Mr. Patrick  32.0    male

[891 rows x 3 columns]

In [15]:
# Display column names with 'a'
titanic_df.filter(like = 'a')

     PassengerId  Pclass  ... Cabin  Embarked
0              1       3  ...   NaN         S
1              2       1  ...   C85         C
2              3       3  ...   NaN         S
3              4       1  ...  C123         S
4              5       3  ...   NaN         S
..           ...     ...  ...   ...       ...
886          887       2  ...   NaN         S
887          888       1  ...   B42         S
888          889       3  ...   NaN         S
889          890       1  ...  C148         C
890          891       3  ...   NaN         Q

[891 rows x 7 columns]

In [16]:
# # Sorting a feature in a DatFrame
titanic_df.filter(like = 'Fare').sort_values(by = 'Fare', ascending = True)
# Descending oder 
# titanic_df.filter(like = 'Fare').sort_values(by = 'Fare', ascending = False)

         Fare
271    0.0000
597    0.0000
302    0.0000
633    0.0000
277    0.0000
..        ...
438  263.0000
341  263.0000
737  512.3292
258  512.3292
679  512.3292

[891 rows x 1 columns]

In [17]:
# Sorting instances in a DatFrame 
titanic_df.sort_values(by = 'Fare', ascending=True)

     PassengerId  Survived  Pclass  ...      Fare        Cabin  Embarked
271          272         1       3  ...    0.0000          NaN         S
597          598         0       3  ...    0.0000          NaN         S
302          303         0       3  ...    0.0000          NaN         S
633          634         0       1  ...    0.0000          NaN         S
277          278         0       2  ...    0.0000          NaN         S
..           ...       ...     ...  ...       ...          ...       ...
438          439         0       1  ...  263.0000  C23 C25 C27         S
341          342         1       1  ...  263.0000  C23 C25 C27         S
737          738         1       1  ...  512.3292         B101         C
258          259         1       1  ...  512.3292          NaN         C
679          680         1       1  ...  512.3292  B51 B53 B55         C

[891 rows x 12 columns]

In [18]:
titanic_df.describe()
# The describe() method provides a quick overview of the numerical data in a DataFrame. 
# As the Name, Sex, Ticket, Cabin, and Embarked columns are textual data, these are by default not taken into account by the describe() method.

       PassengerId    Survived      Pclass  ...       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  ...  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642  ...    0.523008    0.381594   32.204208
std     257.353842    0.486592    0.836071  ...    1.102743    0.806057   49.693429
min       1.000000    0.000000    1.000000  ...    0.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000  ...    0.000000    0.000000    7.910400
50%     446.000000    0.000000    3.000000  ...    0.000000    0.000000   14.454200
75%     668.500000    1.000000    3.000000  ...    1.000000    0.000000   31.000000
max     891.000000    1.000000    3.000000  ...    8.000000    6.000000  512.329200

[8 rows x 7 columns]

In [19]:
# Display unique values 
titanic_df["Pclass"].unique()

array([3, 1, 2])

In [20]:
# Query using 'and' & 'or'
titanic_df.query("Sex == 'male' & Fare == 0")

     PassengerId  Survived  Pclass  ... Fare Cabin  Embarked
179          180         0       3  ...  0.0   NaN         S
263          264         0       1  ...  0.0   B94         S
271          272         1       3  ...  0.0   NaN         S
277          278         0       2  ...  0.0   NaN         S
302          303         0       3  ...  0.0   NaN         S
413          414         0       2  ...  0.0   NaN         S
466          467         0       2  ...  0.0   NaN         S
481          482         0       2  ...  0.0   NaN         S
597          598         0       3  ...  0.0   NaN         S
633          634         0       1  ...  0.0   NaN         S
674          675         0       2  ...  0.0   NaN         S
732          733         0       2  ...  0.0   NaN         S
806          807         0       1  ...  0.0   A36         S
815          816         0       1  ...  0.0  B102         S
822          823         0       1  ...  0.0   NaN         S

[15 rows x 12 columns]

In [21]:
# Query using 'and' & 'or'
titanic_df.query("Pclass == 3 | Ticket == 'LINE'")

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
2              3         1       3  ...   7.9250   NaN         S
4              5         0       3  ...   8.0500   NaN         S
5              6         0       3  ...   8.4583   NaN         Q
7              8         0       3  ...  21.0750   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
882          883         0       3  ...  10.5167   NaN         S
884          885         0       3  ...   7.0500   NaN         S
885          886         0       3  ...  29.1250   NaN         Q
888          889         0       3  ...  23.4500   NaN         S
890          891         0       3  ...   7.7500   NaN         Q

[491 rows x 12 columns]

In [22]:
# titanic_df.loc[:,:]
# titanic_df.loc[10:20,:]
titanic_df.loc[10:20,["Pclass", "Cabin", "Embarked"]]

    Pclass Cabin Embarked
10       3    G6        S
11       1  C103        S
12       3   NaN        S
13       3   NaN        S
14       3   NaN        S
15       2   NaN        S
16       3   NaN        Q
17       2   NaN        S
18       3   NaN        S
19       3   NaN        C
20       2   NaN        S

In [23]:
titanic_df.iloc[10:20,2:5]
# iloc takes row indexes & column indexes upto N-1

    Pclass                                               Name     Sex
10       3                    Sandstrom, Miss. Marguerite Rut  female
11       1                           Bonnell, Miss. Elizabeth  female
12       3                     Saundercock, Mr. William Henry    male
13       3                        Andersson, Mr. Anders Johan    male
14       3               Vestrom, Miss. Hulda Amanda Adolfina  female
15       2                   Hewlett, Mrs. (Mary D Kingcome)   female
16       3                               Rice, Master. Eugene    male
17       2                       Williams, Mr. Charles Eugene    male
18       3  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female
19       3                            Masselmani, Mrs. Fatima  female

In [24]:
# Droping rows and columns
titanic_df.drop([0,2,3,4,5,6,7,8], axis = 0) # axis = 0, indicates to drop rows
# titanic_df.drop(["Ticket","Cabin"], axis = 1) # axis = 1, indicates to drop columns

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
1              2         1       1  ...  71.2833   C85         C
9             10         1       2  ...  30.0708   NaN         C
10            11         1       3  ...  16.7000    G6         S
11            12         1       1  ...  26.5500  C103         S
12            13         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[883 rows x 12 columns]

In [25]:
titanic_df

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]