In [2]:
import pandas as pd
reviews = pd.read_excel("./reviews.xlsx")
pd.set_option('display.max_rows', 5)

In [12]:
# reviews: Refers to the Pandas DataFrame containing your data.
# .rename(columns={'points': 'score'}): Renames the column 'points' to 'score' within the DataFrame.

#     columns specifies that you're renaming columns.
#     {'points': 'score'} is a dictionary mapping the old column name to the new one.

reviews.rename(columns={'points': 'score'})

,country,description,designation,score,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,93,35.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
15,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,93,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [14]:
# reviews: Refers to the Pandas DataFrame containing your data.
# .rename(index={0: 'firstEntry', 1: 'secondEntry'}): Renames the index labels 0 and 1 to 'firstEntry' and 'secondEntry' respectively.

#     index specifies that you're renaming index labels.
#     0: 'firstEntry' and 1: 'secondEntry' map the old index labels to the new ones.
    
reviews.rename(index={0: 'firstEntry', 1: 'secondEntry'})

,country,description,designation,score,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
firstEntry,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
secondEntry,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,93,35.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
15,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,93,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [ ]:
1. side by side
    1. axis=1
    2. merge or join
2. stacking
    1. axis=0
    2. concat or append

In [ ]:

axis=1 in pd.concat() means that you're concatenating DataFrames along the columns.
Breakdown:

    axis=0 (default): Concatenates DataFrames vertically, stacking them one on top of the other.
    axis=1: Concatenates DataFrames horizontally, placing them side by side.

In [ ]:


Visual Representation:

axis=0 (default):

df1:
   A  B
0  1  3
1  2  4

df2:
   A  B
0  5  7
1  6  8

Concatenated DataFrame:
   A  B  A  B
0  1  3  5  7
1  2  4  6  8

In [ ]:
axis=1:

df1:
   A  B
0  1  3
1  2  4

df2:
   A  B
0  5  7
1  6  8

Concatenated DataFrame:
   A  B  A  B
0  1  3  5  7
1  2  4  6  8

In [45]:
import pandas as pd

df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})
print(df1)
print(df2)

# Concatenate along rows
df_concat_rows = pd.concat([df1, df2], axis=0)
print('======concat=====axis=0, ==')
print(df_concat_rows)

# Concatenate along columns
df_concat_cols = pd.concat([df1, df2], axis=1)
print('======concat=====axis=1, ==')
print(df_concat_cols)

   A  B
0  1  3
1  2  4
   A  B
0  5  7
1  6  8
======concat=====axis=0, ==
   A  B
0  1  3
1  2  4
0  5  7
1  6  8
======concat=====axis=1, ==
   A  B  A  B
0  1  3  5  7
1  2  4  6  8

In [ ]:
merge
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html

In [ ]:
DataFrame.merge(right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=False, 
                suffixes=('_x', '_y'), copy=None, indicator=False, validate=None)

how{‘left’, ‘right’, ‘outer’, ‘inner’, ‘cross’}, default ‘inner’

In [60]:
import pandas as pd

# Sample DataFrames
df1 = pd.DataFrame({'key': ['K0', 'K1', 'K2'], 'A': ['A0', 'A1', 'A2'], 'B': ['B0', 'B1', 'B2']})
df2 = pd.DataFrame({'key': ['K1', 'K2', 'K3'], 'C': ['C0', 'C1', 'C2'], 'D': ['D0', 'D1', 'D2']})
print(df1)
print(df2)

merged_inner = pd.merge(df1, df2, on='key', how='inner')
print('============merged_inner===============')
print(merged_inner)

merged_left = pd.merge(df1, df2, on='key', how='left')
print('============merged_left===============')
print(merged_left)

merged_right = pd.merge(df1, df2, on='key', how='right')
print('============merged_right===============')
print(merged_right)

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
  key   C   D
0  K1  C0  D0
1  K2  C1  D1
2  K3  C2  D2
============merged_inner===============
  key   A   B   C   D
0  K1  A1  B1  C0  D0
1  K2  A2  B2  C1  D1
============merged_left===============
  key   A   B    C    D
0  K0  A0  B0  NaN  NaN
1  K1  A1  B1   C0   D0
2  K2  A2  B2   C1   D1
============merged_right===============
  key    A    B   C   D
0  K1   A1   B1  C0  D0
1  K2   A2   B2  C1  D1
2  K3  NaN  NaN  C2  D2

In [64]:
merged_left = pd.merge(df1, df2, left_on='key', right_on='key', how='left')
print('============merged_left===============')
print(merged_left)

============merged_left===============
  key   A   B    C    D
0  K0  A0  B0  NaN  NaN
1  K1  A1  B1   C0   D0
2  K2  A2  B2   C1   D1