In [145]:
# 📂 Importing Pandas

In [146]:
import pandas as pd

In [147]:
# Creating DataFrames
# 1️⃣ From a Dictionary

data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35], 'City': ['NY', 'LA', 'SF']}
df = pd.DataFrame(data)
print(df)

      Name  Age City
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF

In [148]:
# From a CSV File
df = pd.read_csv("./data.csv")  # Load CSV into a DataFrame

In [149]:
# 3️⃣ From an Excel File

df = pd.read_excel('data.xlsx')

In [150]:
# 🔍 Exploring Data

df.head()  # First 5 rows

      Name  Age     City
0    Alice   25       NY
1      Bob   30       LA
2  Charlie   35       SF
3    David   28  Chicago
4      Eve   40    Miami

In [151]:
df.tail()  # Last 5 rows

      Name  Age     City
0    Alice   25       NY
1      Bob   30       LA
2  Charlie   35       SF
3    David   28  Chicago
4      Eve   40    Miami

In [152]:
df.info()  # Summary of DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [153]:
df.describe()  # Summary statistics

            Age
count   5.00000
mean   31.60000
std     5.94138
min    25.00000
25%    28.00000
50%    30.00000
75%    35.00000
max    40.00000

In [154]:
df.shape  # (rows, columns)

(5, 3)

In [155]:
df.columns  # List of column names

Index(['Name', 'Age', 'City'], dtype='object')

In [156]:
df.dtypes  # Data types of each column

Name    object
Age      int64
City    object
dtype: object

In [ ]:
# 🎯 Selecting Data

In [ ]:
# 1️⃣ Selecting Columns

In [157]:
df['Name']  # Single column (Series)

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: Name, dtype: object

In [158]:
df[['Name', 'Age']]  # selecting/Filtering Multiple columns (DataFrame)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   28
4      Eve   40

In [159]:
# 2️⃣ Selecting Rows (Indexing)

In [160]:
df.iloc[0]  # First row (by position)

Name    Alice
Age        25
City       NY
Name: 0, dtype: object

In [161]:
df.loc[0]  # First row (by label)

Name    Alice
Age        25
City       NY
Name: 0, dtype: object

In [162]:
df.loc[1:2, ['Name', 'Age']]  # Specific rows & columns

      Name  Age
1      Bob   30
2  Charlie   35

In [163]:
# 3️⃣ Filtering Data

df[df['Age'] > 25]  # Filter rows where Age > 25

      Name  Age     City
1      Bob   30       LA
2  Charlie   35       SF
3    David   28  Chicago
4      Eve   40    Miami

In [164]:
df[df['City'] == 'NY']  # Filter rows where City = 'NY'

    Name  Age City
0  Alice   25   NY

In [165]:
# 🛠️ Modifying Data

In [166]:
# 1️⃣ Adding/Inserting a Column

In [171]:
df['Salary'] = [50000, 60000, 70000, 80000, 90000]

In [ ]:
# 2️⃣ Updating Values

df.loc[0, 'Age'] = 26  # Update a specific value

In [ ]:
df['Age'] = df['Age'] + 1  # Increment all ages by 1

In [ ]:
# 3️⃣ Removing Columns

df.drop(columns=['Salary'], inplace=True)

In [ ]:
# 4️⃣ Removing Rows

df.drop(index=1, inplace=True)  # Remove row with index 1

In [ ]:
# 📌 Sorting & Grouping
# 1️⃣ Sorting Data
df.sort_values(by='Age', ascending=False)

In [ ]:
# 2️⃣ Grouping Data

df.groupby('City')['Age'].mean()  # Average age per city

In [ ]:
# 📈 Working with Missing Data

df.isnull().sum()  # Check missing values
df.fillna(0, inplace=True)  # Replace missing values with 0
df.dropna(inplace=True)  # Remove rows with missing values

In [ ]:
# 📤 Exporting Data

df.to_csv('output.csv', index=False)
df.to_excel('output.xlsx', index=False)